project: 
  type: website

website: 
  page-navigation: true
  title: "URI BES Colloquium Series" 
  site-url: "https://marineevoecolab.github.io/BES-Colloquium/" 
  repo-url: "https://github.com/MarineEvoEcoLab/BES-Colloquium/"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    left: |
      [![](https://raw.githubusercontent.com/MarineEvoEcoLab/BES-Colloquium/main/content/IMG/URILogo.png){fig-alt="URI" width=100px}](https://uri.edu)
    right: | 
      [![](https://raw.githubusercontent.com/MarineEvoEcoLab/BES-Colloquium/main/content/IMG/URIBrandmark.png){fig-alt="Think Big" width=150px}](https://uri.edu)
    center: "&copy; CC-1.0-Jon Puritz and URI BES Program"


  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/MarineEvoEcoLab/BES-Colloquium/main/content/IMG/BES_Logo_small.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://web.uri.edu/cels/academics/bes/
        text: "URI BES Program"
#      - icon: github
#        href: https://github.com/nmfs-opensci
#        text: "NMFS OpenSci"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Previous Colloquiums"  
        contents:
        - href: content/Colloquium_Fall_2023.qmd
          text: "Fall 2023"
        - href: content/Colloquium_Spring_2024.qmd
          text: "Spring 2024"
        - href: content/Colloquium_Fall_2024.qmd
          text: "Fall 2024"
        - href: content/Colloquium_Spring_2025.qmd
          text: "Spring 2025"
      - href: content/Nominations.qmd
        text: "Nomination Process"
      - href: content/Hosting.qmd
        text: "Hosting a speaker"
      - href: content/Meeting.qmd
        text: "How to meet with a speaker"
      

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    grid:
      margin-width: 150px
#      gutter-width: 0.50em
      body-width: 900px




filters:
  - include-files.lua
  - quarto

  
