---
title: "University of Rhode Island Biological and Environmental Sciences"
subtitle: "Colloquium Series"
page-layout: full
---

The BES Colloquium Series is the research seminar series for the [College of Environmental Sciences](https://web.uri.edu/cels/) at the University of Rhode Island.  BES students nominate speakers from across several disciplines including: Cell and Molecular Biology (CMB), Ecology and Ecosystem Science (EES), Environmental and Earth Sciences (EVES), Evolution and Marine Biology (EMB), and Sustainable Agriculture and Food Systems (SAFS).  Invited speakers spend the day at URI visiting with faculty and graduate students.

## Spring 2024 Schedule

**Time:** 3:00 PM
**Location:** CBLS 010

| Date  | Specialization | Speaker                  | Speaker's Affiliation                          | Speaker's Website                                    |
|-------|----------------|--------------------------|-----------------------------------------------|---------------------------------------------|
| Jan 26| all            | BES Grad Reps            | URI                                           | [URI BES Grad Reps](https://web.uri.edu/cels/academics/bes/)           |
| Feb 2 | EMB            | Dr. Yaamini Venkataraman | WHOI                                          | [Dr. Yaamini Venkataraman](https://yaaminiv.github.io/about/)         |
| Feb 9 | CMB            | Michael Metzger          | Pacific Northwest Research Institute           | [Michael Metzger](https://pnri.org/metzger-lab/)                        |
| Feb 16| Education       | Dr. Angela Google         | URI                                           | [Dr. Angela Google](https://web.uri.edu/cels/2022-college-of-the-environment-and-life-sciences-new-faculty/) |
| Feb 23| SAFS           | Benton Taylor             | Harvard                                       | [Benton Taylor](https://taylorlab.oeb.harvard.edu/)                     |
| Mar 1 | EVES           | Dr. James Heiss           | UMASS Lowell                                  | [James Heiss](https://www.jamesheiss.com/)                                                                        |
| Mar 8 | CMB            | Concetta DiPace           | Oxford Nanopore Technologies                  | [Concetta DiPace](https://www.linkedin.com/in/concetta-dipace-phd-20384525/) |
| Mar 22|                |                           |                                               |                                                                         |
| Mar 29|                |                           |                                               |                                                                         |
| Apr 5 | EES            | Dr. Kevin Olival          | EcoHealth Alliance                            | [Dr. Kevin Olival](https://www.ecohealthalliance.org/personnel/dr-kevin-olival) |
| Apr 12|                |                           |                                               |                                                                         |
| Apr 19| SAFS           | Dr. Ray Kaplan            | SGU                                           | [Dr. Ray Kaplan](https://www.sgu.edu/research/sgu-research/ray-m-kaplan-dvm-phd-dacvm-devpc/) |
| Apr 26| EMB            | Dr. Katie McFarland        | NOAA                                          | [Dr. Katie McFarland](https://www.fisheries.noaa.gov/contact/katie-mcfarland-phd) |

: Spring 2024 {.striped .hover}


## Overview
The M.S. and Ph.D. in Biological and Environmental Sciences (BES) are interdisciplinary, interdepartmental graduate degrees with faculty from multiple departments in the College of the Environment and Life Sciences (CELS), including Biological Sciences; Cell and Molecular Biology; Fisheries, Animal and Veterinary Science; Geosciences; Natural Resources Science; Nutrition and Food Sciences; and Plant Sciences; as well as faculty from the Graduate School of Oceanography.

