---
title: Colloquium Fall 2023
repo-actions: false
---

| Date       | Speaker                  | Speaker's Affiliation                           | Speaker's Website                                                     | Talk Title                                                                                                                                           |
|------------|--------------------------|------------------------------------------------|-----------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sep. 15th  | BES Grad Reps            | URI                                            | [BES Grad Reps](https://web.uri.edu/cels/academics/bes/)             | Orientation & Welcome BBQ                                                                                                                           |
| Sept. 22nd | Carlos Prada              | URI                                            | [Carlos Prada](https://web.uri.edu/bio/meet/carlos-prada/)           | Ecology, adaptation, and speciation in corals: Ecology driving reproductive isolation in broadcast spawners                                           |
| Sept. 29th | Dr. Devon Lukow           | Yale                                           | [Dr. Devon Lukow](https://medicine.yale.edu/profile/devon-lukow/)   | "Chromosomal instability accelerates the evolution of resistance to anti-cancer therapies"                                                           |
| Oct. 6th   |                          |                                                |                                                                       |                                                                                                                                                      |
| Oct. 13th  | Blake Ushijima            | UNC-Wilmington                                 | [Blake Ushijima](https://www.ushijima-lab.com/)                      |                                                                                                                                                      |
| Oct. 20th  | Dr. Nic Fisk              | URI                                            | [Dr. Nic Fisk](https://fisklab.github.io/)                           |                                                                                                                                                      |
| Oct. 27th  | Dr. Carol Bocetti         | Pennsylvania Western University                | [Dr. Carol Bocetti](https://www.linkedin.com/in/carol-bocetti-30b906258/) | "Collaborative Conservation saves the Kirtland's Warbler and serves as a model for all conservation-reliant species and ecosystems"                 |
| Nov. 3rd   | Dr. Emil Ruff              | Marine Biological Laboratory - Woods Hole, MA | [Dr. Emil Ruff](https://rufflab.org/2022/11/28/emil-ruff/)          | Microbial production of “dark oxygen”: An overlooked process in Earth’s hidden ecosystems                                                            |
|            |                           |                                                |                                                                       | Emil will talk about the microbial production of oxygen in the absence of light and its potential relevance in anoxic subsurface ecosystems. ...    |
| Nov. 10th  | Heather Spalding           | College of Charleston                          | [Heather Spalding](https://biology.cofc.edu/about-the-department/faculty-staff-listing/spalding-heather.php) | A multidisciplinary outlook on understanding a cryptogenic species in the Papahan̄aumokuak̄ea Marine National Monument, Hawai‘i                     |
| Nov. 17th  | Natchee Barnd (ZOOM)       | Oregon State University                        | [Natchee Barnd](https://natchee-barnd.squarespace.com/)             | "Indigenous Ocean and Coast: Designing a Collaborative Marine Studies Course"                                                                          |
| Dec. 1st   | Amanda Gallinat            | Colby College                                  | [Amanda Gallinat](https://www.amandagallinat.com/)                  |                                                                                                                                                      |
| Dec. 8th   | Specialization/BES Meeting |                                                |                                                                       |                                                                                                                                                      |


: Fall 2023 {.striped .hover}



