---
title: Hosting
repo-actions: false
---

## Detailed Hosting Instructions

Detailed hosting instructions can be found [here](https://docs.google.com/document/d/1qHLMf6Y00UmRL330I4FvGEDkEE5Womd89utthv7dpF4/edit?usp=sharing)


## Important Logistical Details

### At least two weeks prior to the visit

* Prepare a flyer to announce the talk
   * Contact the speaker to ask them to:
      * Approve the flyer
* Confirm all travel arrangements:
   * Ask if they need to be picked up at the airport or the train station, and get their arrival and departure information.
   * If they are traveling by car - share with them information about parking at URI (where to park and how to secure a visitors parking pass by registering their car). 
      * Provide them with detailed directions to CBLS.
   * Exchange cell phone numbers.
* Coordinate one-on-one meetings
   * If they want to meet with somebody in particular, arrange for a one-on-one meeting with that particular person.
   * Set up a draft of their visit calendar  - It is up to the host to arrange individual or group meetings with individual faculty and/or students and/or colleagues. This is encouraged!
* Email the flyer and the seminar announcement to Jon Puritz
   * Jon Puritz will announce seminars on the Wednesday prior to the seminar (at the latest) and on Friday via the different groups (CELS, BES Faculty, BES Students, BES postdocs). 
* Pizza lunch for students and the speaker will be announced to CELS grad students and BES 581/BES 582 students.  Please encourage students to attend the week you are hosting.  

### During the visit

* Host the speaker to all their meetings, or make sure somebody else does.
* At the pizza lunch and before the talk - VERY IMPORTANT:  Ensure that there is a sign-up sheet with the name of the speaker, and that ALL ATTENDANTS fill it.   
   * They should include:  Name, Affiliation, and if they are student, faculty or visitor. 
* Please also make sure to clean up the conference room after lunch.  Feel free to distribute extra food to graduate students who were unable to attend.
* Compile all documents and email to the Admin Assistant to let them know you have uploaded them to the folder.


