---
title: Nomination Process
repo-actions: false
---

## How to nominate a speaker

### Philosophy
Our nomination process helps to ensure equity and transparency in the speaker selection process and to ensure timely nominations and invitations.  

::: {.callout-important}
A reminder to faculty that nominations must be from students.  
:::

### Process
Here are the steps in our nomination process for Fall 2025:

1. Students submit nominations using this [form](https://forms.gle/kz8F2PC2LYgve2jx9).  Nominations are due by October 31st, 2025
2. The student's primary advisor must approve the nomination.  
3. Graduate Student Reps will rank nominations within each specialization
4. Jon Puritz (EMB Coordinator and BES Colloquium Instructor) will make final nomination (and backup choices) by Nov 8, 2025 based on rankings and funding for speaker travel.

::: {.callout-note}
Specializations without nominations will forfeit their slots at this time.  Nominations do not carry over, so if yours wasn't selected last semester, please nominate again.
:::

All rankings and invitations will be posted in a spreadsheet open to the community.


